# Generated by Django 6.0.7 on 2026-08-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='roles.permission'),
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
    ]
