# Generated by Django 6.0.7 on 2026-08-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_role_options_remove_role_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom du rôle'),
        ),
    ]
