# Generated by Django 6.0.7 on 2026-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_role_created_at_role_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
